### ISSUE TITLE
Add support and tests for running on windows

### ISSUE THREAD

**Issue by mikeblakeuk** [mozilla/sops#1011]
Although sops is designed for Lunix/WSL/bash it would be nice to support Windows\PowerShell

My current workaround is to duplicate the paths. (I don't really want to do a hectic regex)
```yaml
  - path_regex: .*/rings/dev/.*
    azure_keyvault: https://blah
  - path_regex: .*\\rings\\dev\\.*
    azure_keyvault: https://blah
```
