### ISSUE TITLE
Using https://pkg.go.dev/go.mozilla.org/sops/decrypt doesn't work with age encrypted file?

### ISSUE THREAD

**Issue by steffakasid** [mozilla/sops#1019]
Hi,

I encrypted a file using my age key located in `~/.age/key.age`. I set SOPS_AGE_KEY_FILE="/Users/steffenrumpf/.age/key.age". And was able to encrypt/decrypt my file using sops. But when trying to reading the file in my go tool. I got: `No keys found in file.` error in go.

Regards
Steffen

**Comment by knoppi** [comment]
Hi, since I encountered the same error message recently and people might find this issue: you get this message, when you have no recipient defined in your encrypted file. In my case, I had an age recipient but was using SOPS version 3.6.1 -- before the age integration (that happened with SOP 3.7.0).

Example:

```
---
apiVersion: v1
kind: Secret
metadata:
    name: some_name
    namespace: some_namespace
stringData:
    values-prod: ENC[AES256_GCM,data:REDACTED,type:str]
    values-test: ENC[AES256_GCM,data:REDACTED,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: REDACTED
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            REDACTED
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-16T13:58:48Z"
    mac: ENC[AES256_GCM,data:REDACTED,type:str]
    pgp: []
    encrypted_regex: values-.*
    version: 3.7.1
```

SOPS >= 3.7.0 finds the age entry, SOPS pre 3.7.0 effectively sees this file:


```
---
apiVersion: v1
kind: Secret
metadata:
    name: some_name
    namespace: some_namespace
stringData:
    values-prod: ENC[AES256_GCM,data:REDACTED,type:str]
    values-test: ENC[AES256_GCM,data:REDACTED,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: "2022-08-16T13:58:48Z"
    mac: ENC[AES256_GCM,data:REDACTED,type:str]
    pgp: []
    encrypted_regex: values-.*
    version: 3.7.1
```

And it has "No keys found in file".
