### ISSUE TITLE
YAML streams with encrypted and plaintext documents

### ISSUE THREAD

**Issue by imranismail** [mozilla/sops#1058]
I have a use case to decrypt a stream of YAML documents that includes an unencrypted document:

Example:

**.sops.yaml**

```yaml
creation_rules:
  - encrypted_regex: "^(data|stringData)$"
    kms: <redacted>
```

**/dev/stdin**

```yaml
apiVersion: v1
data:
  password: ENC[...]
kind: Secret
metadata:
  name: mysecret
sops:
  age: []
  azure_kv: []
  encrypted_regex: ^(data|stringData)$
  gcp_kms: []
  hc_vault: []
  kms: [...]
  lastmodified: "2022-05-13T14:37:39Z"
  mac: ENC[...]
  pgp: []
  version: 3.7.3
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: nginx
        name: myapp
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
```

```sh
$> sops --decrypt --input-type=yaml --output-type=yaml /dev/stdin
$> MAC mismatch. File has <redacted>, computed <redacted>
```

How can I do this today with sops?
