### ISSUE TITLE
Breaking multiline formating in yaml as soon as a line end with a space

### ISSUE THREAD

**Issue by n0rad** [mozilla/sops#1180]
:wave: 

As soon as a line in a multiline value end with a space, sops breaks the multiline formatting and convert to single line with `\n`

```yaml
test: |
  line one
  line two with space at the end 
  line three
```

```
$ sops --version
sops 3.7.3 (latest)
$ sops -e test.yaml > test.enc.yaml
$ sops -d test.enc.yaml
test: "line one\nline two with space at the end \nline three\n"
```

**Comment by felixfontein** [comment]
The content of the YAML is identical, it's only the YAML formatting that changes. If you load both versions with a YAML parser, you obtain the same result. That's intentional, sops never promised to keep the formatting of YAML, only the content.

**Comment by n0rad** [comment]
Sure, I know that it's the same content, but if I do:
```yaml
test: |
  line one
  line two **without** space at the end
  line three
```
```bash
$ sops -e test.yaml > test.enc.yaml
$ sops -d test.enc.yaml
test: |
    line one
    line two **without** space at the end
    line three
```

As anyone would expected.

When using sops to store configuration file encrypted in git for example, coming back to the configuration file and having it one lined definitely break the user experience.

**Comment by felixfontein** [comment]
> definitely break the user experience.

I strongly disagree on that. The aim is to emit an equivalent YAML file containing the same information (including comments). That's what sops does, and what happens in your case as well.

If you want to retain formatting of the YAML file, you probably have to look for another tool. Alternatively let sops encrypt the YAML file as binary data, then you get the exact same content back.

**Comment by n0rad** [comment]
So let me explain the full workflow with the real use case, maybe I'm doing it wrong:

I'm using `sops` with `age` to commit `kubernetes` secrets to `git` and let [flux](https://fluxcd.io/flux/guides/mozilla-sops/#encrypting-secrets-using-age) applying it. 
I setup a `.sops.yaml` file in a parent folder with the public key and  [configuration](https://fluxcd.io/flux/guides/mozilla-sops/#configure-the-git-directory-for-encryption) to encrypt data part of secrets.
I'm using [vscode-sops](https://marketplace.visualstudio.com/items?itemName=signageos.signageos-vscode-sops) VScode plugin to call sops as soon as an encrypted file is open, to edit and re-encrypting file when closing it.

Using this workflow all I have to do to edit a secret in VScode is to open, edit, close, commit.

I hit the issue while trying to encrypt [wireguard](https://www.wireguard.com/) configuration file.

```yaml
apiVersion: v1
stringData:
    wg0.conf: |
        [Interface]
        Address = 10.43.0.1/24
        ListenPort = 6530
        PrivateKey = EM2K6hssd2G3snCZqk2LsAe/gzvhtwerMTbKCff7iVNvvv0tWI=

        [Peer]
        # srv42
        PublicKey = faFB5CfMSzxlvfxvfdv7X7CZfFtudGVDr+YxnUitcyMuO57u6i9jU=
        AllowedIPs = 10.43.0.2/32

kind: Secret
metadata:
    name: wireguard-server
    namespace: default
```

The workflow is working perfectly as expected, until I wanted to add a second peer so I open the file and prepare the configuration block. But I did not had the public key yet so closed the file as is:

```yaml
apiVersion: v1
stringData:
    wg0.conf: |
        [Interface]
        Address = 10.43.0.1/24
        ListenPort = 6530
        PrivateKey = EM2K6hssd2G3snCZqk2LsAe/gzvhtwerMTbKCff7iVNvvv0tWI=

        [Peer]
        # srv42
        PublicKey = faFB5CfMSzxlvfxvfdv7X7CZfFtudGVDr+YxnUitcyMuO57u6i9jU=
        AllowedIPs = 10.43.0.2/32

        [Peer]
        # srv43
        PublicKey = 
        AllowedIPs = 10.43.0.3/32

kind: Secret
metadata:
    name: wireguard-server
    namespace: default
```

and re-opened it when I had the key but the unencrypted version is now:

```yaml
apiVersion: v1
stringData:
    wg0.conf: "[Interface]\nAddress = 10.43.0.1/24\nListenPort = 6530\nPrivateKey = EM2K6hssd2G3snCZqk2LsAe/gzvhtwerMTbKCff7iVNvvv0tWI=\n\n[Peer]\n# srv42\nPublicKey = faFB5CfMSzxlvfxvfdv7X7CZfFtudGVDr+YxnUitcyMuO57u6i9jU=\nAllowedIPs = 10.43.0.2/32\n\n[Peer]\n# srv43\nPublicKey = \nAllowedIPs = 10.43.0.3/32\n"
kind: Secret
metadata:
    name: wireguard-server
    namespace: default
```

Yes YAML content is technically identical, but it's now unmaintainable.

As you guest it, it would be the same for any plain secret file you want to push to kubernetes and any situation where you would leave a trailing space at any line in the configuration file.

**Comment by joel-teratis** [comment]
@n0rad have you found a solution for this? This is unfortunate for maintaining yaml files in git.

**Comment by haslersn** [comment]
@n0rad you can store the Secret's values in sops-encrypted files and assemble them into a Kubernetes Secret by putting the following in your `kustomization.yaml`:

```yaml

generators:
  - |
    apiVersion: viaduct.ai/v1
    kind: ksops-exec
    metadata:
      name: secret-generator
    secretFrom:
      - metadata:
          name: wireguard-server
        files:
          - wg0.ini
```

Since `.ini` is supported by sops, you can even encrypt only the private key by using the following `.sops.yaml`:

```yaml
creation_rules:
  - encrypted_regex: "^(PrivateKey)$"
```
