### ISSUE TITLE
In Kubernetes, how to create a sops secret from a binary file ? 

### ISSUE THREAD

**Issue by HugoRh** [mozilla/sops#1200]
Hi !

I'm struggling with that one, all my secrets are maintained with SOPS, recently I had to integrate a binary file as a secret but I can't seem to make it work...
I can update in place the binary file but I can't integrate it in a template...
Anyone has a method to achieve that ?

Thanks !!

**Comment by anutator** [comment]
You can encrypt any file using variable:

secrets.yml (enccrypted by SOPS+age)
```yml
secretEnvFile:
    private.pem: ENC[AES256_GCM,data:jf6g3AW0RPRBuTC+LCTzjVPjzhqfeRFoNMg8M5lnQp3TTHn0fXwA+SjdETX3HbWZxo+UvcR8D5afnfmCmsRylYVMzvunnqD0b3zHpN502KN5zamcwt1/uN2NsLDSqdZNvHoboZSDgv6Oe+FijgFfbIM5CJvUKfyHMjCzWA61JhzfD+0Mklz+DnCggfgfgf...
```

values.yml (not encrypted)
```
volumeMounts:
- name: jwt
  mountPath: /app/jwt/
  readOnly: true
.....
...

```

Export this private.pem as file (I also use pluck to get divverent variables for dev, text etc.

_helpers.tpl

```go
{{- define "GetSecretFiles" -}}
{{- with .Values.secretEnvFile }}
{{- range $k, $v := . }}
{{ $k }}: {{ $v | b64enc }}
{{- end }}{{- end }}
{{- with .Values.secretTiersFile }}
{{- range $k, $v := . }}
{{ $k }}: {{ pluck $.Values.TIER $v | first | default $v._default | b64enc }}
{{- end }}{{- end }}
{{- end }}
```

secret-jwt.yml

```yml
{{- $fullName := include "GetAppFullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" $fullName "jwt" }}
  labels: {{- include "GetLabels" . | nindent 4 }}
type: Opaque
data:
{{- include "GetSecretFiles" . | indent 2 }}
```

deployment.yml — use secret as volume

```yml
.....
      volumes:
      - name: jwt
        secret:
          secretName: {{ printf "%s-%s" $fullName "jwt" }}
          defaultMode: 0444
,,,,,
      containers:
      - name: {{ $fullName }}
       .....
        volumeMounts: {{- toYaml .Values.volumeMounts | default "" | nindent 10 }}
```
