### ISSUE TITLE
go-sops doesn't grab correct/all roles from .sops.yaml

### ISSUE THREAD

**Issue by ckolos** [mozilla/sops#136]
Using go-sops to create a file destined for use in dev ends up creating a file that only contains the hiera-sops-prod roles, not dev or stage.
Reproduce:
```
$ which sops
/home/ckolos/go/bin/sops
$ sops app/foo
<save file in editor>
$ grep hiera-sops-dev app/foo
$

Compare this to the python code:
$ sops.sh app/bar
<a bunch of sops output>
<save file in editor>
ckolos@gojira:
$ grep hiera-sops-dev app/bar
                "role": "arn:aws:iam::<dev IAM acct number>:role/hiera-sops-dev" 
$
```

**Comment by autrilla** [comment]
@ckolos can you share your .sops.yaml (hiding the actual IAMs etc)

**Comment by ckolos** [comment]
@autrilla - once i redact all the things in the file, it looks pretty grim.
```
# creation rules are evaluated sequentially, the first match wins
creation_rules:
    # upon creation of a file that matches the pattern *.dev.yaml,
    # one KMS in the DEV IAM and one KMS in prod will be used, and
    # a PGP key is used for backup
    - filename_regex: '(^|/|\.)dev(\.[\w_-]+)?\.(yaml|json|txt|key)$'
      kms: 'arn:aws:kms:<prod-region>:<dev-iam>:key/fe86dd69-4132-404c-ab86-4269956b4500+arn:aws:iam::<dev-iam>:role/hiera-sops-dev,arn:aws:kms:<prod-region>:<prod-iam>:key/5052f06a-5d3f-489e-b86c-57201e06f31e+arn:aws:iam::<prod-iam>:role/hiera-sops-prod'
      pgp: '6F..D'

    # similar pattern for stage files
    - filename_regex: '(^|/|\.)stage(\.[\w_-]+)?\.(yaml|json|txt|key)$'
      kms: 'arn:aws:kms:<prod-region>:<stage-iam>:key/846cfb17-373d-49b9-8baf-f36b04512e47+arn:aws:iam::<stage-iam>:role/hiera-sops-stage,arn:aws:kms:<prod-region>:<prod-iam>:key/5052f06a-5d3f-489e-b86c-57201e06f31e+arn:aws:iam::<prod-iam>:role/hiera-sops-prod'
      pgp: '6F..D'

    # prod files use two KMS in the PROD IAM but in different regions
    - filename_regex: '(^|/|\.)prod(\.[\w_-]+)?\.(yaml|json|txt|key)$'
      kms: 'arn:aws:kms:<prod-region>:<prod-iam>:key/5052f06a-5d3f-489e-b86c-57201e06f31e+arn:aws:iam::<prod-iam>:role/hiera-sops-prod, arn:aws:kms:<other-prod-region>:<prod-iam>:key/cb1fab90-8d17-42a1-a9d8-334968904f94+arn:aws:iam::<prod-iam>:role/hiera-sops-prod'
      pgp: '6F..D'

    # Finally, if the rules above have not matched, this one is a
    # catchall that will encrypt the file using one KMS in DEV,
    # one KMS in stage and two in PROD, plus the PGP file. This is
    # useful for common files
    - kms: 'arn:aws:kms:<prod-region>:<dev-iam>:key/fe86dd69-4132-404c-ab86-4269956b4500+arn:aws:iam::<dev-iam>:role/hiera-sops-dev,arn:aws:kms:<prod-region>:<stage-iam>:key/846cfb17-373d-49b9-8baf-f36b04512e47+arn:aws:iam::<stage-iam>:role/hiera-sops-stage,arn:aws:kms:<prod-region>:<prod-iam>:key/5052f06a-5d3f-489e-b86c-57201e06f31e+arn:aws:iam::<prod-iam>:role/hiera-sops-prod, arn:aws:kms:<other-prod-region>:<prod-iam>:key/cb1fab90-8d17-42a1-a9d8-334968904f94+arn:aws:iam::<prod-iam>:role/hiera-sops-prod'
      pgp: '6F..D'
```
