### ISSUE TITLE
Support encryption context in .sops.yaml

### ISSUE THREAD

**Issue by rouge8** [mozilla/sops#159]
It would be great if in addition to specifying the KMS key in `.sops.yaml`, we could also specify the encryption context to use. Our use case would be combining this with `filename_regex` so that files matching a certain pattern would be encrypted with a specific context.

**Comment by autrilla** [comment]
On `.sops.yaml` you can specify more than one KMS key (you specify a comma separated list of ARNs) per entry. How would you specify the context? Would this be per entry, or per key?

**Comment by rouge8** [comment]
I was thinking it might make sense to use the same format as in the encrypted files, i.e.:

```yaml
kms:
  - arn: kms1
    context:
      foo: bar
  - arn: kms2
```

**Comment by autrilla** [comment]
This has been fixed by #238, something like this is now possible:

```
creation_rules:
    - key_groups:
      - kms:
        - arn: arn1
          role: role1
          context:
            foo: bar
        - arn: arn2
```

Note that this is only supported inside `key_groups`.
