### ISSUE TITLE
In decrypt mode, support extracting one key/branch only

### ISSUE THREAD

**Issue by jvehent** [mozilla/sops#19]
It would be useful to support extracting only a subsection of a `sops` encrypted file. For example, given the file:

```yaml
branchA:
    keyA: valueA
branchB:
    keyB: value B
```
The following command should extract `branchA.keyA` only:
```bash
$ sops -d -q 'branchA'->'keyA' file.yaml 
```
or something similar.
