### ISSUE TITLE
Support YAML lists for KMS keys in .sops.yaml file?

### ISSUE THREAD

**Issue by goodspark** [mozilla/sops#239]
If one wants to use multiple KMS keys in the sops config file, they must all be on the same line, comma-delimited. If this were broken into lists, it'd be much easier to maintain and read this file!

Another ask is to allow breaking out the key ARN and an assume role ARN.

Current:
```yaml
creation_rules:
  - filename_regex: myfile.yaml
    # This is a really long line that's tedious to read/parse/edit
    kms: arn:aws:kms:us-west-1:1:key/1+arn:aws:iam::2:role/Thing,arn:aws:kms:us-west-1:3:key/3+arn:aws:iam::4:role/Thing,arn:aws:kms:us-west-1:4:key/4
```

Desired:
```yaml
creation_rules:
  - filename_regex: list_support.yaml
    kms:
    # Allow single-line ARNs for ARN+roles
    - arn:aws:kms:us-west-1:3:key/3+arn:aws:iam::4:role/Thing
    # Allow single-line for ARNs
    - arn:aws:kms:us-west-1:4:key/4
    # Additional ask: Support breaking out roles too!
    - arn: arn:aws:kms:us-west-1:1:key/1
      role: arn:aws:iam::2:role/Thing

  # But for legacy support also allow the old way!
  # Plus for simpler configs this can be more concise while still readable
  - filename_regex: old_way_is_ok_too.yaml
    kms: arn:aws:kms:us-west-1:1:key/1
```
