### ISSUE TITLE
Sops --set destroys yaml structure (3.0.2)

### ISSUE THREAD

**Issue by abferm** [mozilla/sops#297]
I started with:
```
db:
    passwords:
        root_user: ENC...
...
```
After running `sops --set '["db"]["passwords"]["user1"] "user1password"' secrets.yaml` I ended up with:
```
root_user: ENC...
user1: ENC...
```

```
$ sops --version
sops 3.0.2 (latest)
```
