### ISSUE TITLE
Encrypting a file which contains encrypted data will re-encrypt those values

### ISSUE THREAD

**Issue by omerlh** [mozilla/sops#311]
Let's say I have this file:
```
appSecrets:
    dbPassword: ENC[AES256_GCM,data:7k+usg==,iv:E4juEMzJPUVs64rXABfaLAe/z5DNAOgyFRArFkiExfY=,tag:7T5ESWXaBkLIkmKd8OT1pQ==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/<>/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2018-03-28T11:21:56Z'
        enc: CiQAYTWkxo55Y+sdAc4gyUWV1ohLz6ZAvQQhB5V3Y4kK7M6ye1ISSQCqcM6mD631Nm0OibWZTKE5ETy8uxbMKRL0wg4WgYOcSyECWT3wi/jSiC/SCEXxJEB6hziQbmU5NQmL6PNpaHwrcYpmr1Wi10I=
    lastmodified: '2018-03-28T11:21:58Z'
    mac: ENC[AES256_GCM,data:xGk/Sr6pWi5+NsPByPb/J74ltTXzGWUq+nzxcwl2Ab05TLwf9CeT7yyJZJeSH8aPBP73vsF+D4OCByfTdd3gWhGnp2OBv5YxsSejL224Chye8kgQmXXMixt03JChRy9oZyDmzhrvCoznOBRTmQCD9q8gtChRZN2/512Z2ClQeHU=,iv:2usZDOe9ZUG9Fx3/O5X9mp5S2oo7UVO6eRX/rd/8V9U=,tag:TQjsStRxdtWKZvIW1XBfMQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.0.2
```
Now, if I want to add a new key to this yaml, let's say something like this:
```
appSecrets:
    dbPassword: ENC[AES256_GCM,data:7k+usg==,iv:E4juEMzJPUVs64rXABfaLAe/z5DNAOgyFRArFkiExfY=,tag:7T5ESWXaBkLIkmKd8OT1pQ==,type:str]
   otherPassword: top secret
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/<>/locations/global/keyRings/sops/cryptoKeys/sops-key
        created_at: '2018-03-28T11:21:56Z'
        enc: CiQAYTWkxo55Y+sdAc4gyUWV1ohLz6ZAvQQhB5V3Y4kK7M6ye1ISSQCqcM6mD631Nm0OibWZTKE5ETy8uxbMKRL0wg4WgYOcSyECWT3wi/jSiC/SCEXxJEB6hziQbmU5NQmL6PNpaHwrcYpmr1Wi10I=
    lastmodified: '2018-03-28T11:21:58Z'
    mac: ENC[AES256_GCM,data:xGk/Sr6pWi5+NsPByPb/J74ltTXzGWUq+nzxcwl2Ab05TLwf9CeT7yyJZJeSH8aPBP73vsF+D4OCByfTdd3gWhGnp2OBv5YxsSejL224Chye8kgQmXXMixt03JChRy9oZyDmzhrvCoznOBRTmQCD9q8gtChRZN2/512Z2ClQeHU=,iv:2usZDOe9ZUG9Fx3/O5X9mp5S2oo7UVO6eRX/rd/8V9U=,tag:TQjsStRxdtWKZvIW1XBfMQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.0.2
```
Now, if I'll run sops:
```
sops --encrypt --gcp-kms projects/<>/locations/global/keyRings/sops/cryptoKeys/sops-key -i config.yml
```
The entire file will be encrypted again - meaning the key `dbPassword` will be encrypted twice.
Is that the intended behavior?
