### ISSUE TITLE
Comment encryption/decryption using --encrypted-suffix

### ISSUE THREAD

**Issue by RoryShively** [mozilla/sops#328]
I have a use case where I want to be able to commit a partially encrypted file to my git repo and be able to decrypt and re-encrypt on the fly without SOPS munging my data

config.enc.yaml
```
# Unencrypted Config
name: cluster-service-base-test
app_label: cluster-service-base-test

# Encrypted Config
secrets:
    secret_key: ENC[AES256_GCM,data:gBtWcZPHF/b/9jM=,iv:Zj5bsPvMiHkgHkPmmo4G3YgFHfgx8D7KCffrRY1UbUY=,tag:JB0yBcqXYYWI+aklDnMxQg==,type:str]

sops:
    kms:
    -   arn: ...
        created_at: ...
        enc: ...
    gcp_kms: ...
    lastmodified: ...
    mac: ...
    pgp: []
    encrypted_suffix: sercrets
    version: 3.0.3
```

I would like to have sops keep my comments in place but if I decrypt this partially encrypted file the comments get deleted.

config.dec.yaml
```
name: cluster-service-base-test
app_label: cluster-service-base-test
secrets:
    secret_key: 1234
```
