### ISSUE TITLE
"sops --set" documentation doesn't give enough information for users to actually use the feature

### ISSUE THREAD

**Issue by exarkun** [mozilla/sops#336]
Based on https://github.com/mozilla/sops#set-a-sub-part-in-a-document-tree and a document roughly like:

```yaml
foo: ...
data:
  x: ...
  y: ...
sops:
  ...

I would expect to  be able to do something like:

```shell
sops --set "[\"data\"][\"foo\"] \"bar\"" secrets.enc.yaml
```

However, the resulting diff deletes all of the top-level keys (except "sops") in the encrypted sops document and promotes all of the contents of `data` to top-level keys (in other words, terribly corrupts the document).

So either this usage (strongly implied by the README) is incorrect or the functionality of sops itself is broken.
