### ISSUE TITLE
path_regex not working

### ISSUE THREAD

**Issue by stefanthorpe** [mozilla/sops#342]
I have the following .sops.yaml, but my regex isn't working as I expected:

```
creation_rules: 
    
  # KMS service for development 
  - path_regex: ^(.\/development\/.*)
    gcp_kms: projects/versus-development/locations/us-east1/keyRings/versus-development-key-ring/cryptoKeys/versus-development-key
   
  # KMS service for infra 
  - path_regex: ^(.\/infra\/.*) 
    gcp_kms: projects/versus-infra-dev/locations/us-east1/keyRings/versus-infra-dev-key-ring/cryptoKeys/versus-infra-dev-key
```
Both these gcp_kms work without the path_regex but with the regex in place the top one is applied.

What I'm trying to do is apply a regex pattern for the directory the file is in.
