### ISSUE TITLE
Multi-document support

### ISSUE THREAD

**Issue by draeron** [mozilla/sops#350]
yaml multi document `---` doesn't seems to be supported. I understand this might be a limitation of how sops work, but then it should be specified in the readme.

```yaml
---
data: some-data
---
data: some-other-data
```
