### ISSUE TITLE
Support AWS profile setting in creation_rules

### ISSUE THREAD

**Issue by max-rocket-internet** [mozilla/sops#389]
Hi,

We have a `.sops.yaml` file like this:

```
creation_rules:
  - path_regex: secrets/environments/production/secrets.yaml
    kms: 'arn:aws:kms:us-east-1:666666666:key/xxxx-x-xxxxx'
  - path_regex: secrets/environments/staging/secrets.yaml
    kms: 'arn:aws:kms:us-east-1:3333333333:key/xxxx-x-xxxxx'
```

We have many different keys spread across different accounts. Normally when we are switching between working with different files we have to change our `AWS_PROFILE` environment variable to match a profile that is associated with the account that has the KMS key. It's fine but it's a bit of a pain.

It would be cool if we could have this:

```
creation_rules:
  - path_regex: secrets/environments/production/secrets.yaml
    kms: 'arn:aws:kms:us-east-1:666666666:key/xxxx-x-xxxxx'
    aws_profile: 'production'
  - path_regex: secrets/environments/staging/secrets.yaml
    kms: 'arn:aws:kms:us-east-1:3333333333:key/xxxx-x-xxxxx'
    aws_profile: 'staging'
```

Then we would never have to worry about setting and changing the `AWS_PROFILE` environment variable 🙂
