### ISSUE TITLE
YAML multi-document encryption discards documents after first

### ISSUE THREAD

**Issue by bmhatfield** [mozilla/sops#456]
Hi there,

YAML multi-document encryption appears to have been implemented in this PR, about 6 months ago: https://github.com/mozilla/sops/pull/392

However, I have a simple multi-document file like (filename `my-secrets.secret.yml`):

```yml
---
apiVersion: v1
kind: Secret
metadata:
    name: my-first-secret
type: Opaque
data:
    GF_AUTH_GOOGLE_CLIENT_ID: BASE64-ENCODED-SECRET
    GF_AUTH_GOOGLE_CLIENT_SECRET: BASE64-ENCODED-SECRET
---
apiVersion: v1
kind: Secret
metadata:
    name: my-other-secret
type: Opaque
data:
    client_id: BASE64-ENCODED-SECRET
    client_secret: BASE64-ENCODED-SECRET
```

I've tried this with and without the leading `---`, and SOPS is generating an encrypted file for only the first document. The second document is not present in the output at all.

Has there been a regression? I'm using SOPS in a very simple invocation:

`sops --encrypt --gcp-kms $KEYPATH $FILENAME > $ENCRYPTED_FILENAME`
