### ISSUE TITLE
--rotate --in-place results in empty file if user cannot decrypt

### ISSUE THREAD

**Issue by hobti01** [mozilla/sops#484]
Related to #365 , the following scenario results in an empty file (unexpected) instead of a failure (expected) or no action:

* create .sops.yaml:
```
creation_rules:
  - path_regex: test.yaml
    key_groups:
      - pgp:
        # userA
        - FD43E10B0D145AA3E865E3088554CA96EF7FF338
        # userB
        - 75385B17ADC57E09BA14A523A7208B9C8B55CCB8
```
* create test.yaml
```
$ sops test.yaml
```
* modify .sops.yaml, removing userB (yourself)
```
creation_rules:
  - path_regex: test.yaml
    key_groups:
      - pgp:
        # userA
        - FD43E10B0D145AA3E865E3088554CA96EF7FF338
```
* update keys
```
$ sops updatekeys -y test.yaml
...
2019/06/26 09:57:28 File test.yaml synced with new keys
```
* rotate data key to remove access for removed user
```
$ sops -r -i test.yaml ; echo $?
0
# I would expect 'Failed to get the data key required to decrypt the SOPS file.' and no change to test.yaml
$ cat test.yaml
$
```

The purpose of rotating the data key after updating the user keys is to prevent removed users from decrypting the files.

Am I approaching this the wrong way?
