### ISSUE TITLE
Only string keys are supported

### ISSUE THREAD

**Issue by sham126** [mozilla/sops#493]
Hi All,

I'm feeling like I'm losing the plot as this simply example should work but when I try to encode my secret.yaml file, against aws kms, I get the following error:

> $ helm secrets enc secret.yaml 
> Encrypting secret.yaml
> Error encrypting tree: Error walking tree: Tree contains a non-string key (type yaml.MapSlice): [{include "app.fullname" . <nil>}]. Only string keys aresupported
> Error: plugin "secrets" exited with error

The file looks like this:

```
apiVersion: v1
stringData:
  app.yaml_encrypted: |-
    database:
      jdbc-user: username
      jdbc-password: password

kind: Secret
metadata:
  name: {{ include "app.fullname" . }}`
```

As you can see I've also tried to use the _encrypted suffix to encrypt just that value but that doesn't stop sops going through the yaml... Surely there's not an issue using curly braces, as we're using it to insert helm values?

This is my .sops.yaml in root directory:

```
---
creation_rules:
        # Encrypt with AWS KMS
        - kms: 'xxxxxxxxxxxxx'
          encrypted_suffix: _encrypted
```

**Comment by autrilla** [comment]
That YAML is not what you might think it is. This is the equivalent:

```yaml
--- 
apiVersion: v1
kind: Secret
metadata: 
  name: 
    ? 
      ? "include \"app.fullname\" ."
      : ~
    : ~
stringData: 
  app.yaml_encrypted: |-
      database:
        jdbc-user: username
        jdbc-password: password
```

The `?` indicates a "complex mapping key". SOPS only allows strings to be keys.
