### ISSUE TITLE
Support substitution of key parameters from path_regex captures

### ISSUE THREAD

**Issue by kshpytsya** [mozilla/sops#506]
I would like to be able to write something like this:

```yaml
creation_rules:
- path_regex: 'secrets\.(.*)\.(.*).yaml'
  key_groups:
  - kms:
    - arn: arn:aws:kms:eu-central-1:999999:alias/sops-\2-\1
  - kms:
    - arn: arn:aws:kms:us-west-1:9999999:alias/sops-\2-\1
      role: something-\1-more
      context:
        a: \1
        b: xxx-\2
```
