### ISSUE TITLE
Missing --unencrypted-regex option

### ISSUE THREAD

**Issue by yogeek** [mozilla/sops#538]
The `--encrypted-regex` option already exists. Why does the equivalent exist for unencrypted keys ?
It would be more flexible than using the `--unencrypted-suffix` option that forces to have only one suffix value

**Comment by autrilla** [comment]
I can't think of a reason other than that no one has needed it or put in the time to implement it

**Comment by yogeek** [comment]
@autrilla ok thank you. Is it possible to make a PR to suggest the feature if we do not propose the implementation or do we do it through this issue ?

**Comment by autrilla** [comment]
This issue is enough. I’ve labeled it appropriately.

**Comment by dfredell** [comment]
I think we have a use case for a unencrypted-regex config as well. We are using terraform to manage the config in GitLab. In particular we have our CI/CD environment variables in sops. It would be nice to not encrypt the `key`, `masked`, and `type` items, but encrypt everything else. 

Here is my ideal secrets.yml file. 
```yaml
root:
    webhooks:
        gitlab_alerts: ENC[AES256_GCM,data:jCQGsFihmAViwDiCMndgl6HjHSs8A==,type:str]
    secrets:
        customer_repo:
        -   key: DOCKER_AUTH_CONFIG
            value: ENC[AES256_GCM,data:LfCz7HsExkfAzjw30EGcr/OS/=,+uuQ==,type:str]
            masked: true
        -   key: TERRAFORM_DEPLOY_KEY_BASE64
            value: ENC[AES256_GCM,data:OeSsRag:N2/X8K2x88Ii0X80rGun9Q==,type:str]
            type: file
            masked: true
```

Currently I'm using a `.sops.yaml` of
```yaml
reation_rules:
  - path_regex: secrets.yaml
    unencrypted_suffix: key
```
which provides the most value, but it would be nice to see the `masked` value during a code review.
