### ISSUE TITLE
How to encrypt a file locally with an assumed KMS role and decrypt it AWS without any role

### ISSUE THREAD

**Issue by zioalex** [mozilla/sops#555]
### Problem description:
I am going to use Sops in Aws EKS. The current workflow presume that the developer will encrypt a secret assuming a special role. Later, such encrypted file, is used in AWS and needs to be decrypted without such role ( The AWS node has the proper access to do it )
Follow my .sops.yaml file
```
 creation_rules:
   - key_groups:
     - kms:
       - arn: "arn:aws:kms:us-east-1::XXXXXXXXXXXXX:key/kms_key_id"
         role: "arn:aws:iam::XXXXXXXXXXXXX:role/EncryptionRole"
     - kms:
       - arn: "arn:aws:kms:us-east-1:XXXXXXXXXXXXX:key/kms_key_id"
```
With the above config the encryption process will fail because the user cannot use the 2 key directly, even though is the same.
My current workaround is to comment the last 2 lines from the .sops.yaml, encrypt the file, and remove the "role:" line from the encrypted file.
In this way I can decrypt the key in AWS.

### Ideas
Have the possibility to specify which key to use to decrypt
Rewrite the encrypted the file with the specified arn independently from the one used for encryption
Other ideas are welcome.
