### ISSUE TITLE
Yaml with numeric keys is not processed 

### ISSUE THREAD

**Issue by vitali-shcharbin** [mozilla/sops#653]
Having following yaml:
```
user:
  version: 1
  versions:
    1: some-value
```

Fails with:
```
Error encrypting tree: Error walking tree: Tree contains a non-string key (type int): %!s(int=1). Only string keys aresupported
```

The reason is key "1" is number, changing to "1a" solves the problem, but I think it will be good if parser will support keys which contain only numbers.
