### ISSUE TITLE
Windows: cannot decrypt file in subdirectory

### ISSUE THREAD

**Issue by johngriffinbd** [mozilla/sops#701]
I cloned a repo onto my local windows machine which uses sops for secrets encryption. The repo structure is as follows:
```
// "root"
-- ".sops.yaml"
    // "tf-env"
        // "test"
        -- "terraform.auto.tfvars.enc.json"
```

The contents of the `.sops.yaml` look like this: 
```
---
creation_rules:
  - path_regex: "tf-envs/test/terraform.auto.tfvars.json"
    azure_keyvault: "https://myazurekey.vault.azure.net/keys/my-key-name/MY_KEY"
    encrypted_suffix: "_sensitive"

  - path_regex: "tf-envs/test/terraform.auto.tfvars.enc.json"
    azure_keyvault: "https://myazurekey.vault.azure.net/keys/my-key-name/MY_KEY"
    encrypted_suffix: "_sensitive"
```
After logging to my azure account (which has access to the azure keyvault) via the cli:

`az login`

I then decrypt the secret file using the command at the root folder level:

`sops --decrypt tf-envs/test/terraform.auto.tfvars.enc.json > tf-envs/test/terraform.auto.tfvars.json`

When this command is run in a Linux terminal the secrets file is successfully decrypted. However, when the same command is run in either PowerShell or Command Prompt, sops returns this error:

`error loading config: no matching creation rules found`
