### ISSUE TITLE
Is it possible to cache sops in GitHub Actions

### ISSUE THREAD

**Issue by Dwite** [mozilla/sops#750]
I'm currently using sops in GitHub Actions by installing it via

```
- name: Install sops
  run: go get -u go.mozilla.org/sops/v3/cmd/sops
```

And have tried to cache them via [GitHub Actions Cache for Go](https://github.com/actions/cache/blob/main/examples.md#go---modules)
```
- name: Cache SOPS
  uses: actions/cache@v2
  with:
    path: ~/go/pkg/mod
    key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    restore-keys: |
      ${{ runner.os }}-go-
```

It receives the cache
```
Cache Size: ~0 MB (22 B)
/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/ff3117ba-d412-4ddd-a7c4-b3e259d069c2/cache.tzst -P -C /home/runner/work/projectName/projectName
Cache restored from key: Linux-go-
```

But still installs the sops from scratch
