### ISSUE TITLE
`directory_regex` support (or something similar)?

### ISSUE THREAD

**Issue by chroto** [mozilla/sops#77]
I have users of our SOPS implementation that would prefer to use subdirectories to determine what encryption keys to use.  Our project structure is as follows:

```
├── engineering
├── ops
├── resources
└── ssl
```

Right now, we have a .sops.yaml file in each directory and require users to cd to the directory before creating a new file.  I get a lot of forgetful users who will create secrets from the top level.

So instead of

```
cd engineering
sops foo
```

we get

```
sops engineering/foo
```

If I could extend the configuration featureset to include a `directory_regex` I can run a regex on the first filename that is checked and see if it matches.  If no match, pass through to the `filename_regex` as it works today.

```
creation_rules:
  - directory_regex: ^engineering/
    kms: '...'
    pgp: '...'
  - directory_regex: ^ops/
    kms: '...'
    pgp: '...'
```

happy to submit a patch if you are interested in accepting

**Comment by jvehent** [comment]
I think it might be a useful feature. We may want to keep the existing `filename_regex` for backward compatibility, and have `directory_regex` only match on the dirname of a path. Another option would be to introduce `path_regex` that matches on both the dirname and basename of a file.

Happy to take a patch!

**Comment by mumoshu** [comment]
@chroto @jvehent It seems like `file_regex` matches against the path rather than the basename as of today!

Reproduction step:

```yaml
creation_rules:
- filename_regex: foo/bar/baz/*
  kms: "arn:aws:kms:myregion:myawsaccount:key/mykeyid"
```

```
$ sops -e foo/bar/baz/test.yaml
```

So, can we close this issue as resolved now?
