### ISSUE TITLE
Possible to use as Kubernetes KMS provider?

### ISSUE THREAD

**Issue by uumo** [mozilla/sops#831]
Hi! I was hoping to use sops as a KMS provider for a Kubernetes master node ( https://kubernetes.io/docs/tasks/administer-cluster/kms-provider/ )

I run a sops keyservice
```
sops keyservice --network unix --address /root/sops/sops.sock
```
And configure Kubernetes to use it:
```
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - kms:
          name: myKmsPlugin
          endpoint: unix:///root/sops/sops.sock
          cachesize: 100
          timeout: 3s
      - identity: {}
```

But I get an error
```
kubectl get secret somesecret -o json | kubectl replace -f -
Error from server (InternalError): error when replacing "STDIN": Internal error occurred: failed get version from remote KMS provider: rpc error: code = Unimplemented desc = unknown service v1beta1.KeyManagementService
```

It seems the protocol buffers of sops / Kubernetes kms aren't compatible

Does anyone know any other projects, or workarounds to use sops as a Kubernetes KMS without going down the rabbit hole learning golang & protocol buffers?
