### ISSUE TITLE
Feature request: support arrays for `age` and `pgp` fields in configuration

### ISSUE THREAD

**Issue by johanfleury** [mozilla/sops#845]
Hey.

It would be great to be able to set age and PGP keys as arrays of strings in the configuration. This would be more in phase with YAML style and would allow putting comments, e.g.:

```
creation_rules:
  - path_regex: \.sops\.yaml$
    […]
    age:
      - age1xxx # Foo
      - age1yyy  # Bar
    pgp:
      - XXX, # Foo
      - YYY  # Bar
```

I believe sops already turns the comma separated value into an array internally, so that shouldn’t change the logic too much.

**Comment by autrilla** [comment]
We'd have to do so in a backwards compatible way, which should be possible. It would be good for the internal sops format to also do this in encrypted files.

**Comment by johanfleury** [comment]
I’ve looked into it thinking I would be able to make a PR, but I couldn’t find any ways to extend the YAML parser to make it parse a comma separated string value into `[]string`.

If I understand correctly, one would create a new type (maybe an alias to `[]string`) and define the `UnmarshalYAML()` function on that type to split the value. Is that correct?

**Comment by johanfleury** [comment]
I found a working example, I’ll try to make a PR.

**Comment by MaxRink** [comment]
at least for PGP there exists an workaround that already works
specify a keygroup and leave the needed keys at one and it will basically behave like the wanted feature
```
  - path_regex: \.bin/secrets.yaml$
    key_groups:
     - pgp:
        - 'k1'  # k1
        - 'k2'  # k2
        ...
        - "kn"  #kn
    encrypted_regex: '^.*(?i)(password)(?-i).*$'
```

**Comment by stawii** [comment]
Same for age since https://github.com/mozilla/sops/commit/50a89c82931425d927e8f10ccff7bcf92c3ee4e5
```yaml
creation_rules:
  - key_groups:
      - age:
          - age1aaaaaaaa
          - age1bbbbbbb
```
Note: this behavior seems to be "side effect" of [Key groups](https://github.com/mozilla/sops#key-groups).
It acts funny with just one group, totally ignoring (but still saving in output if defined) `shamir_threshold` value, and saving metadata without `key_groups` block. But.. it get's job done and that's what I wanted!
