### ISSUE TITLE
.sops.yaml and multiple kms keys

### ISSUE THREAD

**Issue by Tanemahuta** [mozilla/sops#894]
Hello there,
I've got an issue with SOPS 3.7.1 when creating a sops encrypted file.

**steps to reproduce:**
1 create `.sops.yaml` with the following contents (replace placeholders) : 
```yaml 
creation_rules:
  - kms: 'arn:aws:kms:eu-central-1:acc1:alias/key1+arn:aws:iam::acc1:role/my-role'
  - kms: 'arn:aws:kms:eu-central-1:acc2:alias/key2+arn:aws:iam::acc2:role/my-role'
  - kms: 'arn:aws:kms:eu-central-1:acc3:alias/key3+arn:aws:iam::acc3:role/my-role'
```
2 issue a `sops test.yaml` save and exit the editor.
**expected result:**
The values are encrypted with the provided KMS keys in the `.sops.yaml`.
**actual result:**
The values are encrypted with the first KMS key only.
