### ISSUE TITLE
Key rotation with age on 3.7.1 does not respect new keys

### ISSUE THREAD

**Issue by mweinelt** [mozilla/sops#901]
We are running with a creation file like this:

```yaml
---

creation_rules:
  - path_regex: \.sops\.yml$
    shamir_threshold: 1
    key_groups:
      - age:
        - foo
        - bar
```

Creating files encrypted to all members of the key group works. But if we add another key and use `sops -r -i` to rotate the ciphertext, new kews in the key group will not be added as recipients of the .sops.yml file and thus be unable to decrypt it. The ciphertext for existing keys however is properly rotated.

Happens on sops 3.7.1.
