### ISSUE TITLE
Yaml decryption adds unnecessary indentation

### ISSUE THREAD

**Issue by dry4ng** [mozilla/sops#950]
When encrypting/decrypting the same yaml file, sops adds unnecessary indentation:

Before:

```
secret_string: val1
secret_array:
  - string1
  - string2
secret_map:
  sub_var1: string1
  sub_var2: string2
```

After:

```
secret_string: val1
secret_array:
    - string1
    - string2
secret_map:
    sub_var1: string1
    sub_var2: string2
```

sops 3.7.1 (latest)
