### ISSUE TITLE
Git diff doesn't work if .sops.yaml is set

### ISSUE THREAD

**Issue by bandesz** [mozilla/sops#959]
## What is the problem

I've created a `.sops.yaml` file in the root of my git repo and added creation rules for two directories:

```
creation_rules:
  - path_regex: sops/dev/.*
    kms: 'arn:aws:kms:eu-west-1:1231231230:key/mrk-k1'
  - path_regex: sops/production/.*
    kms: 'arn:aws:kms:eu-west-1:1231231230:key/mrk-k2'
```

I've set up everything for `git diff` to work following the documentation.

When I run  e.g. `git diff sops/production/secrets.yaml`, I get:

```
error loading config: no matching creation rules found
fatal: unable to read files to diff
```

This happens as `sopsdiffer` will be called with the following two paths:
 - `/var/folders/1p/kj4p1zcn7qg32x53jfztnfb00000gq/T//MPTcrc_secrets.yaml`
 - `sops/production/secrets.yaml`

And there is no matching rule for the first one.

## Possible workaround

I can pass an empty config file to `sops` in `sopsdiffer` and `git diff` will work.

```
[diff "sopsdiffer"]
	textconv = sops --config empty-file.yaml -d
```
