### ISSUE TITLE
Can initially encrypt a file with age, looks for keys in wrong directory to decrypt on macOS

### ISSUE THREAD

**Issue by ethnt** [mozilla/sops#983]
I've been having an issue using sops with age where I can encrypt a file but I cannot decrypt or edit it again. I've created an age key located at `~/.config/sops/age/keys.txt` and set up my `.sops.yaml` file like this:

```yaml
keys:
  - &user_ethnt age1fd5pp5m5g9gkt7f6a8tngct09sxqpw9u4w3uct83sy0h3xlp7ffsunqsr3
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *user_ethnt
```

In a shell where `$SOPS_AGE_KEY_DIR` is `$HOME/.config/sops/age`, I can run `sops secrets.yaml` and it pops open the editor and I can edit and save without problems. But when I go to run `sops secrets.yaml` a second time, it looks for the age keys in `/Users/ethan/Library/Application Support/sops/age/keys.txt` instead:

```
sops secrets.yaml
Failed to get the data key required to decrypt the SOPS file.

Group 0: FAILED
  age1fd5pp5m5g9gkt7f6a8tngct09sxqpw9u4w3uct83sy0h3xlp7ffsunqsr3: FAILED
    - | failed to open file: open /Users/ethan/Library/Application
      | Support/sops/age/keys.txt: no such file or directory

Recovery failed because no master key was able to decrypt the file. In
order for SOPS to recover the file, at least one key has to be successful,
but none were.
```

Is `$SOPS_AGE_KEY_DIR` not working as intended here?
