### ISSUE TITLE
Binary files are not encrypted when encrypted_suffix is specified

### ISSUE THREAD

**Issue by piotrminkina** [mozilla/sops#986]
Hello,

I'm using 3.7.1 on Ubuntu 20.04.3 LTS. I noticed that binary files are not encrypted by sops, when `encrypted_suffix` is provided in `.sops.yaml`. See below files for an example.

```txt
# secret.txt
this is a secret value
```

```yaml
# .sops.yaml
---
creation_rules:
  - path_regex: 'secret\.txt'
    encrypted_suffix: _encrypted
    key_groups:
      - pgp:
          - ... # valid fingerprint
```

Next enter the following command: `sops -e secret.txt > secret.txt.sopsenc.json`. As a result of this command I get the following file:

```json
{
	"data": "this is a secret value",
	"sops": {
		"...": null,
		"mac": "ENC[...]",
		"pgp": [
			{
				"created_at": "2022-01-10T14:25:14Z",
				"enc": "...",
				"fp": "..."
			}
		],
		"encrypted_suffix": "_encrypted",
		"version": "3.7.1"
	}
}
```

But I expect such a file:
```json
{
	"data_encrypted": "ENC[...]",
	"sops": {
		"...": null,
		"mac": "ENC[...]",
		"pgp": [
			{
				"created_at": "2022-01-10T14:25:14Z",
				"enc": "...",
				"fp": "..."
			}
		],
		"encrypted_suffix": "_encrypted",
		"version": "3.7.1"
	}
}
```

I see two solutions for this case:
1. automatic append value of `encrypted_suffix` key to `data` key name, but in this case `encrypted_regex` still will not work,
2. add new configuration key, like `data_key_name`, that will have value `data_encrypted` in my case, so will work regardless of `encrypted_*` setting.

Thank you in advance for considering my request

Regards
Piotr Minkina
